project:
  type: website
  

website:
  title: "Allen Chen"
  navbar:
      left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
       
      right:
      - icon: github
        href: https://github.com/forajii
      - icon: linkedin
        href: https://www.linkedin.com/in/allen-chen-611aaa294/
      - icon: envelope
        href: mailto:alchen518@gmail.com

      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

execute: 
  freeze: auto

